#!/bin/sh

prog="main"

#
# $prog <$prog>
#
# chkconfig: 2345 90 10
# description: $prog - sdfsdfsdf
#

### BEGIN INIT INFO
# Provides: $prog
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Should-Start:
# Should-Stop:
# Short-Description: $prog
# Description: $prog safsdfsdf.
### END INIT INFO

### -----------------
# This script was created using following sources
#
# http://stackoverflow.com/questions/8124345/call-to-daemon-in-a-etc-init-d-script-is-blocking-not-running-in-background
# https://fedoraproject.org/wiki/Packaging:SysVInitScript#Initscript_template
### -----------------

JAVA_HOME=/usr/java/latest
JAVA_OPTS="-Xmx256m -Xms256m"

# Source function library.
. /etc/rc.d/init.d/functions

# FIXME The pid file should be handled by the executed script
# The pid can be filled in in this script
PIDFILE=/var/run/$prog/running.pid

if [ -z "$DAEMON_USER" ]; then
    DAEMON_USER=$prog
fi

if [ -z "$DAEMON_GROUP" ]; then
    DAEMON_GROUP=$prog
fi

# define some additional options in $RUN_OPTS
RUN_CMD="/some/$prog/bin/$prog"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
[ -e /etc/default/$prog ] && . /etc/default/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $RUN_CMD ] || exit 5
    echo -n $"Starting $prog: "
    export JAVA_HOME
    export JAVA_OPTS
    cd /some/$prog

    nohup runuser $DAEMON_USER ${RUN_CMD} -- --host ${HOST} --port ${PORT} ${RUN_OPTS} >> /some/$prog/logs/$prog.log 2>&1 &

    retval=$?   # last error code
    PID=$!      # pid of last backgrounded process
    [ $retval -eq 0 ] && touch ${lockfile} && success || failure

    # Insert pid into pid file for CentOS killproc function
    [ -d "/var/run/$prog" ] || install -d -o "$DAEMON_USER" -g "$DAEMON_GROUP" -m755 "/var/run/$prog"
    echo
    echo $PID > ${PIDFILE}
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $PIDFILE $prog
    retval=$?
    [ $retval -eq 0 ] && rm -f $lockfile
    echo
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $PIDFILE $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
	rh_status_q && exit 0
	$1
	;;
    stop)
	rh_status_q || exit 0
	$1
	;;
    restart)
	$1
	;;
    reload)
	rh_status || exit 7
	$1
	;;
    status)
	rh_status
	;;
    condrestart|try-restart)
	rh_status || exit 0
	restart
	;;

    *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
	exit 2
esac
exit $?
